apiVersion: v2
name: base-deployment
description: A base helm chart for the smallest of services. It has really limited functionality, but is useful for getting up and running quickly.
type: library
version: 0.1.0
appVersion: "1.16.0"
