namespace: staging
config:
  enabled: true
  values:
    foo: bar

secrets:
  enabled: true
  name: shipments-secret

labels:
  tier: frontend

deployment:
  replicas: 10
  image: "lordrahl/shipments"
  resources:
    memory: "64Mi"
    cpu: "250m"

service:
  targetPort: 8080

ingress:
  host: "ing-shipments.lordrahl.ng"
  annotations:
    kubernetes.io/ingress.class: "alb"
