name: Lint

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
  lint:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Lint
        run: |
          helm lint .


  release:
    name: Release
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
         CR_TOKEN: "${{ secrets.G_ACCESS_TOKEN }}"