name: Lint

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
  lint:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Lint
        run: |
          helm lint .
