name: Lint

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Lint
        run: |
          helm lint .